services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY = ${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET = ${CLOUDINARY_API_SECRET}
      - JWT_SECRET = ${JWT_SECRET}
    depends_on:
      - db 
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  dashboard:
    container_name: dashboard
    image: dashboard
    build:
      context: ./dashboard
      dockerfile: dashboard.dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_API_URL=${APP_API_URL}
    depends_on:
      - backend

volumes:
  pgdata: {}
